update_entities:
  description: >
    Esegue il loading delle entities
  fields:
    forced:
      description: Se forzare il caricamento di tutte le informazioni, come le info delle stanze
      example: True

exec_vimar_sql:
  description: >
    Execute a SQL query on vimar.
  fields:
    sql:
      description: SQL Query
      example: SELECT 1

reload_default:
  description: >
    Reload all entities, removing all, and then reload

reload:
  description: Reload vimar service